# Generated by Django 3.2.4 on 2021-09-24 21:30

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('tests', '0001_initial'), ('tests', '0002_auto_20210922_1847'), ('tests', '0003_auto_20210923_1545'), ('tests', '0004_alter_modelwithconfig_integer_field'), ('tests', '0005_hardcodedmodel_boolean_field'), ('tests', '0006_modelwithnocreatedat_modelwithnomaxage'), ('tests', '0007_auto_20210924_1759'), ('tests', '0008_modelwithintegermaxage')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardCodedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('old_records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hardcodedmodel',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='hardcodedmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ModelWithConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boolean_field', models.BooleanField(default=True)),
                ('integer_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='hardcodedmodel',
            name='boolean_field',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ModelWithNoCreatedAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithNoMaxAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('old_records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modelwithnomaxage',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='modelwithnomaxage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ModelWithIntegerMaxAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boolean_field', models.BooleanField(default=True)),
            ],
        ),
    ]
