# Generated by Django 3.2.4 on 2021-09-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210922_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithconfig',
            name='boolean_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelwithconfig',
            name='integer_field',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
