# Generated by Django 3.2.4 on 2021-09-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_modelwithconfig_integer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardcodedmodel',
            name='boolean_field',
            field=models.BooleanField(default=True),
        ),
    ]
