# Generated by Django 3.2.4 on 2021-09-24 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_modelwithnocreatedat_modelwithnomaxage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modelwithnomaxage',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='modelwithnomaxage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
