# Generated by Django 3.2.4 on 2021-09-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20210924_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithIntegerMaxAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boolean_field', models.BooleanField(default=True)),
            ],
        ),
    ]
