# Generated by Django 3.2.4 on 2021-09-21 22:26

from django.db import migrations, models
import django.db.models.deletion
import django_old_records.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_old_records', '0002_modelconfig_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django_old_records.models.limit_choices_to, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', unique=True),
        ),
    ]
