# Generated by Django 3.2.4 on 2021-09-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_old_records', '0003_alter_modelconfig_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconfig',
            name='mode',
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='export',
            field=models.BooleanField(default=False),
        ),
    ]
